"""initial schema

Revision ID: a35a0bffbd18
Revises: 
Create Date: 2026-08-06 08:53:59.836620
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'a35a0bffbd18'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_records')),
    sa.UniqueConstraint('scope', 'idempotency_key', name='uq_idempotency_scope_key')
    )
    op.create_table('policy_clusters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('canonical_title', sa.Text(), nullable=False),
    sa.Column('topic_key', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_clusters'))
    )
    op.create_table('sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('organization_code', sa.Text(), nullable=True),
    sa.Column('canonical_domain', sa.Text(), nullable=False),
    sa.Column('authority', sa.Enum('A', 'B', 'C', 'D', name='authority_grade'), nullable=False),
    sa.Column('collector_type', sa.Text(), nullable=False),
    sa.Column('schedule_cron', sa.Text(), nullable=True),
    sa.Column('rate_limit_per_min', sa.Integer(), nullable=True),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('copyright_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('adapter_name', sa.Text(), nullable=True),
    sa.Column('adapter_version', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_streak', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_table('tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tag_type', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], name=op.f('fk_tags_parent_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('tag_type', 'code', name='uq_tags_type_code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('raw_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_item_id', sa.Text(), nullable=True),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['raw_content_versions.id'], name=op.f('fk_raw_contents_current_version_id'), use_alter=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_contents_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_contents')),
    sa.UniqueConstraint('source_id', 'canonical_url', name='uq_raw_contents_source_url')
    )
    op.create_index('idx_raw_contents_published', 'raw_contents', ['published_at'], unique=False)
    op.create_table('source_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('discovered_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('changed_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_runs_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_runs'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('object_type', sa.Text(), nullable=False),
    sa.Column('object_id', sa.Text(), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('ip_hash', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('idx_audit_object', 'audit_logs', ['object_type', 'object_id', 'occurred_at'], unique=False)
    op.create_table('business_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_type', sa.Text(), nullable=False),
    sa.Column('tax_type', sa.Text(), nullable=True),
    sa.Column('industry_codes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('region_codes', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('employee_band', sa.Text(), nullable=True),
    sa.Column('revenue_band', sa.Text(), nullable=True),
    sa.Column('interest_topics', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_business_profiles_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_profiles'))
    )
    op.create_table('campaigns',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('campaign_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('audience_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channels', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_campaigns_created_by')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_campaigns_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('document_version', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consents_user_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consents'))
    )
    op.create_table('policy_cluster_items',
    sa.Column('policy_cluster_id', sa.UUID(), nullable=False),
    sa.Column('raw_content_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['policy_cluster_id'], ['policy_clusters.id'], name=op.f('fk_policy_cluster_items_policy_cluster_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['raw_content_id'], ['raw_contents.id'], name=op.f('fk_policy_cluster_items_raw_content_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_cluster_id', 'raw_content_id', name=op.f('pk_policy_cluster_items'))
    )
    op.create_table('raw_content_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_content_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('normalized_text', sa.Text(), nullable=False),
    sa.Column('http_etag', sa.Text(), nullable=True),
    sa.Column('http_last_modified', sa.Text(), nullable=True),
    sa.Column('parser_version', sa.Text(), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_content_id'], ['raw_contents.id'], name=op.f('fk_raw_content_versions_raw_content_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_content_versions')),
    sa.UniqueConstraint('raw_content_id', 'content_hash', name='uq_rcv_content_hash'),
    sa.UniqueConstraint('raw_content_id', 'version_no', name='uq_rcv_content_version')
    )
    op.create_index('idx_raw_versions_hash', 'raw_content_versions', ['content_hash'], unique=False)
    op.create_table('tax_contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('policy_cluster_id', sa.UUID(), nullable=True),
    sa.Column('workflow', sa.Enum('DETECTED', 'UNVERIFIED', 'SOURCE_CONFIRMED', 'ANALYZED', 'REVIEW_PENDING', 'APPROVED', 'SCHEDULED', 'PUBLISHED', 'MONITORING', 'CORRECTED', 'SUPERSEDED', 'ARCHIVED', name='workflow_status'), nullable=False),
    sa.Column('legal', sa.Enum('DISCUSSION', 'BILL_PROPOSED', 'PREANNOUNCED', 'GOV_ANNOUNCED', 'ASSEMBLY_PASSED', 'PROMULGATED', 'EFFECTIVE', 'SUSPENDED', 'ABOLISHED', 'UNKNOWN', name='legal_status'), nullable=False),
    sa.Column('risk', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('one_line_summary', sa.Text(), nullable=True),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('promulgation_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('application_start', sa.Date(), nullable=True),
    sa.Column('application_end', sa.Date(), nullable=True),
    sa.Column('source_confidence', sa.SmallInteger(), nullable=False),
    sa.Column('confidence_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('source_confidence BETWEEN 0 AND 100', name=op.f('ck_tax_contents_source_confidence_range')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_tax_contents_created_by')),
    sa.ForeignKeyConstraint(['current_version_id'], ['content_versions.id'], name=op.f('fk_tax_contents_current_version_id'), use_alter=True),
    sa.ForeignKeyConstraint(['policy_cluster_id'], ['policy_clusters.id'], name=op.f('fk_tax_contents_policy_cluster_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tax_contents_tenant_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tax_contents'))
    )
    op.create_index('idx_tax_contents_dates', 'tax_contents', ['effective_date', 'application_end'], unique=False)
    op.create_index('idx_tax_contents_status', 'tax_contents', ['workflow', 'legal', 'risk'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_content_id', sa.UUID(), nullable=True),
    sa.Column('policy_cluster_id', sa.UUID(), nullable=True),
    sa.Column('prompt_template_id', sa.Text(), nullable=False),
    sa.Column('prompt_version', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Text(), nullable=False),
    sa.Column('model_provider', sa.Text(), nullable=False),
    sa.Column('model_name', sa.Text(), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_amount', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['policy_cluster_id'], ['policy_clusters.id'], name=op.f('fk_ai_analyses_policy_cluster_id')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_ai_analyses_tax_content_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_table('attachments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('raw_content_version_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.Text(), nullable=True),
    sa.Column('byte_size', sa.BigInteger(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('extraction_status', sa.Text(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('malware_scan_status', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['raw_content_version_id'], ['raw_content_versions.id'], name=op.f('fk_attachments_raw_content_version_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('raw_content_version_id', 'content_hash', name='uq_attachments_hash')
    )
    op.create_table('campaign_recipients',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('excluded_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_recipients_campaign_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_campaign_recipients_user_id')),
    sa.PrimaryKeyConstraint('campaign_id', 'user_id', name=op.f('pk_campaign_recipients'))
    )
    op.create_table('consultation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tax_content_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('fk_consultation_requests_assigned_to')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_consultation_requests_tax_content_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_consultation_requests_tenant_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_consultation_requests_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultation_requests'))
    )
    op.create_table('content_sources',
    sa.Column('tax_content_id', sa.UUID(), nullable=False),
    sa.Column('raw_content_version_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('PRIMARY','SECONDARY','REFERENCE')", name=op.f('ck_content_sources_content_sources_role')),
    sa.ForeignKeyConstraint(['raw_content_version_id'], ['raw_content_versions.id'], name=op.f('fk_content_sources_raw_content_version_id')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_content_sources_tax_content_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_content_sources_verified_by')),
    sa.PrimaryKeyConstraint('tax_content_id', 'raw_content_version_id', name=op.f('pk_content_sources'))
    )
    op.create_table('content_tags',
    sa.Column('tax_content_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('is_exclusion', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_content_tags_tag_id')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_content_tags_tax_content_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tax_content_id', 'tag_id', name=op.f('pk_content_tags'))
    )
    op.create_table('content_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_content_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rendered_html', sa.Text(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_content_versions_created_by')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_content_versions_tax_content_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_versions')),
    sa.UniqueConstraint('tax_content_id', 'version_no', name='uq_content_versions_no')
    )
    op.create_table('deliveries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('provider_message_id', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'SENT', 'DELIVERED', 'FAILED', 'BOUNCED', 'CANCELED', name='delivery_status'), nullable=False),
    sa.Column('message_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_deliveries_campaign_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_deliveries_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_deliveries_idempotency_key'))
    )
    op.create_index('idx_deliveries_campaign_status', 'deliveries', ['campaign_id', 'status'], unique=False)
    op.create_table('campaign_contents',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_contents_campaign_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], name=op.f('fk_campaign_contents_content_version_id')),
    sa.PrimaryKeyConstraint('campaign_id', 'content_version_id', name=op.f('pk_campaign_contents'))
    )
    op.create_table('content_evidence',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_content_id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=True),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('raw_content_version_id', sa.UUID(), nullable=False),
    sa.Column('locator', sa.Text(), nullable=False),
    sa.Column('support_type', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint("support_type IN ('DIRECT','INFERRED','CONFLICT')", name=op.f('ck_content_evidence_content_evidence_support_type')),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], name=op.f('fk_content_evidence_content_version_id')),
    sa.ForeignKeyConstraint(['raw_content_version_id'], ['raw_content_versions.id'], name=op.f('fk_content_evidence_raw_content_version_id')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_content_evidence_tax_content_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_evidence'))
    )
    op.create_index('idx_content_evidence_content', 'content_evidence', ['tax_content_id', 'field_name'], unique=False)
    op.create_table('corrections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_content_id', sa.UUID(), nullable=False),
    sa.Column('original_content_version_id', sa.UUID(), nullable=False),
    sa.Column('corrected_content_version_id', sa.UUID(), nullable=False),
    sa.Column('reason_code', sa.Text(), nullable=False),
    sa.Column('reason_detail', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('impact_filter', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_corrections_approved_by')),
    sa.ForeignKeyConstraint(['corrected_content_version_id'], ['content_versions.id'], name=op.f('fk_corrections_corrected_content_version_id')),
    sa.ForeignKeyConstraint(['original_content_version_id'], ['content_versions.id'], name=op.f('fk_corrections_original_content_version_id')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_corrections_tax_content_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corrections'))
    )
    op.create_table('engagement_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('delivery_id', sa.UUID(), nullable=True),
    sa.Column('tax_content_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['deliveries.id'], name=op.f('fk_engagement_events_delivery_id')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_engagement_events_tax_content_id')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_engagement_events_tenant_id')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_engagement_events_user_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_engagement_events'))
    )
    op.create_index('idx_engagement_content_time', 'engagement_events', ['tax_content_id', 'occurred_at'], unique=False)
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tax_content_id', sa.UUID(), nullable=False),
    sa.Column('content_version_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.Enum('APPROVE', 'APPROVE_WITH_EDIT', 'REJECT', name='review_decision'), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('checked_source_version_ids', sa.ARRAY(sa.UUID()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], name=op.f('fk_reviews_content_version_id')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_reviews_reviewer_id')),
    sa.ForeignKeyConstraint(['tax_content_id'], ['tax_contents.id'], name=op.f('fk_reviews_tax_content_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_index('idx_engagement_content_time', table_name='engagement_events')
    op.drop_table('engagement_events')
    op.drop_table('corrections')
    op.drop_index('idx_content_evidence_content', table_name='content_evidence')
    op.drop_table('content_evidence')
    op.drop_table('campaign_contents')
    op.drop_index('idx_deliveries_campaign_status', table_name='deliveries')
    op.drop_table('deliveries')
    op.drop_table('content_versions')
    op.drop_table('content_tags')
    op.drop_table('content_sources')
    op.drop_table('consultation_requests')
    op.drop_table('campaign_recipients')
    op.drop_table('attachments')
    op.drop_table('ai_analyses')
    op.drop_index('idx_tax_contents_status', table_name='tax_contents')
    op.drop_index('idx_tax_contents_dates', table_name='tax_contents')
    op.drop_table('tax_contents')
    op.drop_index('idx_raw_versions_hash', table_name='raw_content_versions')
    op.drop_table('raw_content_versions')
    op.drop_table('policy_cluster_items')
    op.drop_table('consents')
    op.drop_table('campaigns')
    op.drop_table('business_profiles')
    op.drop_index('idx_audit_object', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('source_runs')
    op.drop_index('idx_raw_contents_published', table_name='raw_contents')
    op.drop_table('raw_contents')
    op.drop_table('tenants')
    op.drop_table('tags')
    op.drop_table('sources')
    op.drop_table('policy_clusters')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
